import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mock API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mock API
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Currency Exchange</h2>
            <p>Return exchange rates between the fictional currencies <code>ABC</code> and <code>XYZ</code></p>
            <pre>
              GET {window.location.origin}/api/exchange/{'{from}'}/{'{to}'}
              <br />
              {JSON.stringify({
                from: "from",
                to: "to",
                rate: 1.5
              }, null, 2)}
            </pre>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
